'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { ticketService, authService } from '@/lib/api/services';
import { AlertMessages } from '@/lib/utils/AlertMessages';
import { Button } from '@/components/ui/Button';
import { RouteGuard } from '@/components/auth/RouteGuard';
import { UserRoleEnum, CompanyIdRequestModel } from '@adminvault/shared-models';
import { useAuth } from '@/contexts/AuthContext';
import { Input } from '@/components/ui/Input';
import { TicketCategoryEnum, TicketPriorityEnum, TicketStatusEnum, CreateTicketModel } from '@adminvault/shared-models';
import { Ticket, Calendar } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import { Select } from '@/components/ui/Select';
import { TextArea } from '@/components/ui/TextArea';

const CreateTicketPage: React.FC = () => {
    const router = useRouter();
    const { user } = useAuth();

    useEffect(() => {
        console.log('CreateTicketPage mounted');
    }, []);

    const [isLoading, setIsLoading] = useState(false);
    const [admins, setAdmins] = useState<any[]>([]);
    const [formData, setFormData] = useState({
        subject: '',
        description: '',
        categoryEnum: TicketCategoryEnum.OTHER,
        priorityEnum: TicketPriorityEnum.MEDIUM,
        assignAdminId: '',
        expectedCompletionDate: '',
        ticketCode: ''
    });

    useEffect(() => {
        const fetchAdmins = async () => {
            if (!user?.companyId) return;
            try {
                const response = await authService.getAllUsers(new CompanyIdRequestModel(user.companyId));
                if (response.status && response.data) {
                    const adminUsers = response.data.filter((u: any) =>
                        u.userRole === UserRoleEnum.ADMIN ||
                        u.userRole === UserRoleEnum.SUPER_ADMIN ||
                        u.userRole === UserRoleEnum.SUPPORT_ADMIN
                    );
                    setAdmins(adminUsers);
                }
            } catch (error) {
                console.error('Failed to fetch admins', error);
            }
        };
        fetchAdmins();
    }, [user?.companyId]);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);

        try {
            const model = new CreateTicketModel(
                '', // ticketCode generated by backend
                formData.categoryEnum,
                formData.priorityEnum,
                formData.subject,
                TicketStatusEnum.OPEN,
                undefined, // employeeId - handled by backend
                formData.assignAdminId ? Number(formData.assignAdminId) : undefined,
                formData.expectedCompletionDate ? new Date(formData.expectedCompletionDate) : undefined,
                undefined, // resolvedAt
                undefined, // timeSpentMinutes
                formData.description
            );

            const response = await ticketService.createTicket(model);
            if (response.status) {
                AlertMessages.getSuccessMessage('Ticket created successfully');
                router.push('/tickets');
            } else {
                AlertMessages.getErrorMessage(response.message);
            }
        } catch (error: any) {
            AlertMessages.getErrorMessage(error.message || 'Failed to create ticket');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <RouteGuard>
            <div className="min-h-screen bg-slate-50 dark:bg-slate-900 pb-12">
                <PageHeader
                    title="Create New Ticket"
                    description="Submit a new support request"
                    icon={Ticket}
                />

                <main className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
                    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden">
                        <div className="p-6 md:p-8">
                            <form onSubmit={handleSubmit} className="space-y-6">
                                {/* Subject */}
                                <div>
                                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                                        Subject <span className="text-red-500">*</span>
                                    </label>
                                    <Input
                                        name="subject"
                                        value={formData.subject}
                                        onChange={handleChange}
                                        placeholder="Brief summary of the issue"
                                        required
                                        className="w-full"
                                    />
                                </div>

                                {/* Description */}
                                <div>
                                    <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                                        Description
                                    </label>
                                    <TextArea
                                        name="description"
                                        value={formData.description}
                                        onChange={handleChange}
                                        placeholder="Detailed description of the issue..."
                                        rows={4}
                                        className="w-full"
                                    />
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    {/* Category */}
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                                            Category <span className="text-red-500">*</span>
                                        </label>
                                        <div className="relative">
                                            <Select
                                                name="categoryEnum"
                                                value={formData.categoryEnum}
                                                onChange={handleChange}
                                                options={Object.values(TicketCategoryEnum).map(cat => ({
                                                    value: cat,
                                                    label: cat.replace(/_/g, ' ')
                                                }))}
                                                required
                                            />
                                        </div>
                                    </div>

                                    {/* Priority */}
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                                            Priority <span className="text-red-500">*</span>
                                        </label>
                                        <Select
                                            name="priorityEnum"
                                            value={formData.priorityEnum}
                                            onChange={handleChange}
                                            options={Object.values(TicketPriorityEnum).map(p => ({
                                                value: p,
                                                label: p
                                            }))}
                                            required
                                        />
                                    </div>
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                    {/* Assign Admin */}
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                                            Assign Admin
                                        </label>
                                        <div className="relative">
                                            <Select
                                                name="assignAdminId"
                                                value={formData.assignAdminId}
                                                onChange={handleChange}
                                                options={[
                                                    { value: '', label: 'Select Admin (Optional)' },
                                                    ...admins.map(admin => ({
                                                        value: String(admin.id),
                                                        label: `${admin.fullName} (${admin.userRole})`
                                                    }))
                                                ]}
                                            />
                                        </div>
                                    </div>

                                    {/* Expected Completion Date */}
                                    <div>
                                        <label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">
                                            Expected Completion Time
                                        </label>
                                        <div className="relative">
                                            <Input
                                                type="datetime-local"
                                                name="expectedCompletionDate"
                                                value={formData.expectedCompletionDate}
                                                onChange={handleChange}
                                                className="w-full pl-10"
                                            />
                                            <Calendar className="absolute left-3 top-2.5 h-4 w-4 text-slate-400 pointer-events-none" />
                                        </div>
                                    </div>
                                </div>

                                <div className="pt-4 flex justify-end gap-3">
                                    <Button
                                        type="button"
                                        variant="outline"
                                        onClick={() => router.push('/tickets')}
                                    >
                                        Cancel
                                    </Button>
                                    <Button
                                        type="submit"
                                        variant="primary"
                                        isLoading={isLoading}
                                        disabled={isLoading}
                                        leftIcon={<Ticket className="h-4 w-4" />}
                                    >
                                        Create Ticket
                                    </Button>
                                </div>
                            </form>
                        </div>
                    </div>
                </main>
            </div>
        </RouteGuard>
    );
};

export default CreateTicketPage;