FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY packages/backend/package*.json ./packages/backend/

RUN npm ci

COPY . .

RUN npm run build:backend

CMD ["node", "dist/packages/backend/main.js"]
