FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/frontend/package*.json ./packages/frontend/

RUN npm ci

COPY . .

RUN npm run build:frontend

FROM nginx:alpine
COPY --from=builder /app/dist/packages/frontend /usr/share/nginx/html
COPY documents/deployment/nginx.conf /etc/nginx/conf.d/default.conf
